export const CALCULATE_WEEKLY = "CALCULATE_WEEKLY";
export const CALCULATE_MONTHLY = "CALCULATE_MONTHLY";
export const CALCULATE_BI_WEEKLY = "CALCULATE_BI_WEEKLY";
export const CALCULATE_BI_MONTHLY = "CALCULATE_BI_MONTHLY";
export const SHOW_RESULTS = "SHOW_RESULTS";
